version: "3"
services:
  db:
    image: postgres
    restart: always
    hostname: postgres
    ports:
      - "5432:5432"
  server:
    container_name: server
    depends_on:
      - db
    command: npm i ts-node && npm run build
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
networks:
  internal:
    driver: bridge